project:
  type: website
  output-dir: docs

website:
  title: "Aykut Şimşek's WebPage"
  

  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Blog
        href: posts.qmd
      - text: Organizations
        href: organizations.qmd
      - text: My Studies
        href: MyStudies.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/AykutSimsek
      - icon: linkedin
        href: https://www.linkedin.com/in/aykut-şimşek-652a7b231/
      - icon: instagram
        href: https://www.instagram.com/a.smsk0o0/

  sidebar: 
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: false
    # toc-location: left
    
    theme: cyborg
    #theme: superhero ve darkly vev lux bu da güzel
    css: styles.css
   


editor: visual 

