---
title: "THAT'S ME"
sidebar: false 
---

-\> Here is [MY CV](https://drive.google.com/file/d/1umWm9l1AnwiuAjCYUYSDHWNP4AfholY6/view?usp=drive_link)

# Education

-   Onur Ateş Anadolu Lisesi, Samsun, Turkey, 2016 - 2020
-   Mechanical Engineering, Hacettepe University, Ankara, Turkey, 2020 - 2022
-   Industrial Engineering, Hacettepe University, Ankara, Turkey, 2022 - ongoing.

# Work Experience

## Employements

1.  IEEE Hacettepe, Administrative Coordinator of the Computer Society, 2022-2023.

2.  IoT Turkey, University Representative, 2022-2023.

3.  IEEE Hacettepe, Vice Chairman of the Board of Directors, 2023 - ongoing.

    (***other areas***) \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

    -   2 years as a waiter

    -   1 year as an ice cream seller

    -   2 years as a barista

    -   2 years as a wedding organizer

    -   ( I have not worked in a field related to my profession yet )

## Internships

"I hope this place will fill up in a few months."

# Projects

-   Survey : Quality Dimensions Users Value Most In Smartphones.

# Competencies

-   Programming Languages: Python, Dart, R

-   Computer Aided-Design Softwares: SolidWorks, Catia, AutoCAD

-   Quarto, Git ( Learning Phase )

-   Organizational Leadership ( Devfest 2022, Pura Game Jam 2023, Devfest 2023, ProgrammixV... )

# Hobbies

-   Digital Music Production on FL Stuido.
-   Mobile Application Development ( Starting - Learning Phase ).
-   Smartphone industry and current technology.
