---
title: "My Assignments"
---

***TASK-1 : Differences between R and Python***

***1- Syntax Difference***

**`Assignment Method`**

```{r}
my_name <- "Aykut Simsek"
print(my_name)
```

```{python}
myName = "Aykut Simsek"
print(myName)
```

**`Vectors vs Lists`**

One of the frequently used tools for storing data in Python is `list`. However, in the R language, `vector` are used to store data.

```{r}
# We can use c() function for creating a vector.
my_courses <- c("Data Anlytics", "Quality Management", "Material Science", "Probability and Statistics", "Production Planning and Control", "MUH101")
print(my_courses)
```

```{python}
# We can use [] for creating a list.
myCourses = ["Data Anlytics", "Quality Management", "Material Science", "Probability and Statistics", "Production Planning and Control", "MUH101"]
print(myCourses)
```

**`Indexing`**

```{r}
my_favorite_teacher <- "Erdi Dasdemir"
# It is a real information
my_favorite_teacher[0]   # -> character(0), did not give us "E"

my_numbers <- c(1, 10, 100, 1000)
my_numbers[1]            # -> first element
my_numbers[1:3]          # -> 1 and 3 both included
```

```{python}
myFavoriteTeacher = "Erdi Dasdemir"
# It is a real information
myFavoriteTeacher[0]      # -> gives us "E"

myNumbers = (1, 10, 100, 1000)
myNumbers[0]             # -> first element
myNumbers[1]             # -> second element (not first)
myNumbers[1:3]           # -> 1 included and 3 excluded
```

***TASK-2 : NA Example***

```{r}
library("dslabs")
data(na_example)
print(na_example)

number_of_na <- sum(is.na(na_example))
print(number_of_na)
cat("Bu vektorde toplam", number_of_na, "adet NA bulunmaktadır")
```

```{r}
library("dslabs")
data(na_example)

naless_example <- ifelse(is.na(na_example), 0, na_example)

print(naless_example)

```
